name: Development Test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - "*"

env:
  PALADINS_DEV_ID: ${{ secrets.PALADINS_DEV_ID }}
  PALADINS_API_KEY: ${{ secrets.PALADINS_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build docker image
        run: npm run test
